
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oaivtlxwwpbstlyftmof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9haXZ0bHh3d3Bic3RseWZ0bW9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NTcyODQsImV4cCI6MjA2MzAzMzI4NH0.Pl6a3sG3Xm7-6POJMNBjmfVNLnuwTSwVcpTGmuJ5ZFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true
    },
    global: {
      headers: {
        'apikey': SUPABASE_PUBLISHABLE_KEY,
      },
    },
  }
);
